#!/usr/bin/env node
// .agents/ is the single source of truth for agent assets (tool-neutral: Codex, Cursor, Copilot, Gemini CLI read it).
// Claude Code reads only .claude/, so this script copies .agents/<kind>/<item> -> .claude/<kind>/<item>.
//
//   node scripts/agents-sync.mjs           copy (idempotent)            -> pnpm agents:sync
//   node scripts/agents-sync.mjs --check   no writes; exit 1 on drift   -> pnpm agents:check (part of pnpm check)
//
// Kinds: skills (folders with SKILL.md), hooks, agents, commands, rules. Missing kinds are skipped.
// Items that exist only in .claude/ (for example generated by `openspec init`) are left alone and listed as
// "claude-only" — move them into .agents/ if you want them managed here.
// Why a copy and not a symlink: symlinks on Windows need Developer Mode / admin; copies work everywhere.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KINDS = ["skills", "hooks", "agents", "commands", "rules"];
const check = process.argv.includes("--check");

const files = (dir) =>
  statSync(dir).isDirectory()
    ? readdirSync(dir).flatMap((n) => (n === ".DS_Store" ? [] : files(join(dir, n)).map((f) => join(n, f))))
    : [""];
const same = (a, b) => {
  if (!existsSync(b)) return false;
  if (statSync(a).isDirectory() !== statSync(b).isDirectory()) return false;
  const fa = files(a).sort();
  const fb = files(b).sort();
  if (fa.join("\n") !== fb.join("\n")) return false;
  return fa.every((f) => readFileSync(join(a, f)).equals(readFileSync(join(b, f))));
};

let copied = 0;
let drift = 0;
for (const kind of KINDS) {
  const src = join(root, ".agents", kind);
  const dst = join(root, ".claude", kind);
  if (!existsSync(src)) continue;
  const items = readdirSync(src).filter((n) => n !== ".DS_Store");
  for (const name of items) {
    const from = join(src, name);
    if (kind === "skills" && (!statSync(from).isDirectory() || !existsSync(join(from, "SKILL.md")))) continue;
    const to = join(dst, name);
    const label = `${kind}/${name}`;
    if (same(from, to)) {
      console.log(`ok           ${label}`);
      continue;
    }
    if (check) {
      console.log(`DRIFT        ${label}  (.claude/ differs from .agents/ — run pnpm agents:sync)`);
      drift++;
      continue;
    }
    mkdirSync(dst, { recursive: true });
    rmSync(to, { recursive: true, force: true });
    cpSync(from, to, { recursive: true });
    console.log(`synced       ${label}`);
    copied++;
  }
  if (existsSync(dst)) {
    for (const name of readdirSync(dst)) {
      if (name !== ".DS_Store" && !items.includes(name)) console.log(`claude-only  ${kind}/${name}`);
    }
  }
}
if (check) {
  console.log(`agents-sync --check: ${drift ? `FAIL, ${drift} item(s) drifted` : "PASS"}`);
  process.exit(drift ? 1 : 0);
}
console.log(`${copied} item(s) copied .agents/ -> .claude/ (${relative(process.cwd(), root) || "."})`);
